name: Setup Ubuntu with Python and Pip

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Usa la última versión de Python 3

    - name: Install pip packages
      run: |
        python -m pip install --upgrade pip
        pip install jsonschema

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'  # Usa la versión 20 de Node.js

    - name: Install markdownlint
      run: |
        npm install -g markdownlint-cli
        
    - name: Run validate Doc Schema
      run: python check.py

    - name: Run validate Doc MD lint
      run: python lint.py

    - name: Commit and push results
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add result/
        git commit -m 'Add result files'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
